export type typeCard = {
  name: string,
  suit: string,
  rank: number,
  color: boolean
}

export const emptyTypeCard: typeCard = {
  name: "",
  suit: "",
  rank: 0,
  color: false
}
export const suitsList: [string, string, string, string] = ["♦️", "♣️", "♠️", "♥️"];

// export const deck: typeCard[] = [
//   { name: '2 ♥️', suit: 'Hearts', rank: 2, color: true },
//   { name: '3 ♥️', suit: 'Hearts', rank: 3, color: true },
//   { name: '4 ♥️', suit: 'Hearts', rank: 4, color: true },
//   { name: '5 ♥️', suit: 'Hearts', rank: 5, color: true },
//   { name: '6 ♥️', suit: 'Hearts', rank: 6, color: true },
//   { name: '7 ♥️', suit: 'Hearts', rank: 7, color: true },
//   { name: '8 ♥️', suit: 'Hearts', rank: 8, color: true },
//   { name: '9 ♥️', suit: 'Hearts', rank: 9, color: true },
//   { name: '10 ♥️', suit: 'Hearts', rank: 10, color: true },
//   { name: 'J ♥️', suit: 'Hearts', rank: 11, color: true },
//   { name: 'Q ♥️', suit: 'Hearts', rank: 12, color: true },
//   { name: 'K ♥️', suit: 'Hearts', rank: 13, color: true },
//   { name: 'A ♥️', suit: 'Hearts', rank: 14, color: true },

//   { name: '2 ♦️', suit: 'Diamonds', rank: 2, color: true },
//   { name: '3 ♦️', suit: 'Diamonds', rank: 3, color: true },
//   { name: '4 ♦️', suit: 'Diamonds', rank: 4, color: true },
//   { name: '5 ♦️', suit: 'Diamonds', rank: 5, color: true },
//   { name: '6 ♦️', suit: 'Diamonds', rank: 6, color: true },
//   { name: '7 ♦️', suit: 'Diamonds', rank: 7, color: true },
//   { name: '8 ♦️', suit: 'Diamonds', rank: 8, color: true },
//   { name: '9 ♦️', suit: 'Diamonds', rank: 9, color: true },
//   { name: '10 ♦️', suit: 'Diamonds', rank: 10, color: true },
//   { name: 'J ♦️', suit: 'Diamonds', rank: 11, color: true },
//   { name: 'Q ♦️', suit: 'Diamonds', rank: 12, color: true },
//   { name: 'K ♦️', suit: 'Diamonds', rank: 13, color: true },
//   { name: 'A ♦️', suit: 'Diamonds', rank: 14, color: true },

//   { name: '2 ♣️', suit: 'Clubs', rank: 2, color: false },
//   { name: '3 ♣️', suit: 'Clubs', rank: 3, color: false },
//   { name: '4 ♣️', suit: 'Clubs', rank: 4, color: false },
//   { name: '5 ♣️', suit: 'Clubs', rank: 5, color: false },
//   { name: '6 ♣️', suit: 'Clubs', rank: 6, color: false },
//   { name: '7 ♣️', suit: 'Clubs', rank: 7, color: false },
//   { name: '8 ♣️', suit: 'Clubs', rank: 8, color: false },
//   { name: '9 ♣️', suit: 'Clubs', rank: 9, color: false },
//   { name: '10 ♣️', suit: 'Clubs', rank: 10, color: false },
//   { name: 'J ♣️', suit: 'Clubs', rank: 11, color: false },
//   { name: 'Q ♣️', suit: 'Clubs', rank: 12, color: false },
//   { name: 'K ♣️', suit: 'Clubs', rank: 13, color: false },
//   { name: 'A ♣️', suit: 'Clubs', rank: 14, color: false },

//   { name: '2 ♠️', suit: 'Spades', rank: 2, color: false },
//   { name: '3 ♠️', suit: 'Spades', rank: 3, color: false },
//   { name: '4 ♠️', suit: 'Spades', rank: 4, color: false },
//   { name: '5 ♠️', suit: 'Spades', rank: 5, color: false },
//   { name: '6 ♠️', suit: 'Spades', rank: 6, color: false },
//   { name: '7 ♠️', suit: 'Spades', rank: 7, color: false },
//   { name: '8 ♠️', suit: 'Spades', rank: 8, color: false },
//   { name: '9 ♠️', suit: 'Spades', rank: 9, color: false },
//   { name: '10 ♠️', suit: 'Spades', rank: 10, color: false },
//   { name: 'J ♠️', suit: 'Spades', rank: 11, color: false },
//   { name: 'Q ♠️', suit: 'Spades', rank: 12, color: false },
//   { name: 'K ♠️', suit: 'Spades', rank: 13, color: false },
//   { name: 'A ♠️', suit: 'Spades', rank: 14, color: false },
// ];


export const deck: typeCard[] = [
  { name: '2 ♥️', suit: 'Hearts', rank: 2, color: true },
  { name: '2 ♠️', suit: 'Spades', rank: 2, color: false },
  { name: '2 ♦️', suit: 'Diamonds', rank: 2, color: true },
  { name: '3 ♥️', suit: 'Hearts', rank: 3, color: true },
  { name: '3 ♦️', suit: 'Diamonds', rank: 3, color: true },
  { name: '4 ♥️', suit: 'Hearts', rank: 4, color: true },

  { name: 'A ♥️', suit: 'Hearts', rank: 14, color: true },
  { name: '5 ♥️', suit: 'Hearts', rank: 5, color: true },
  { name: '6 ♥️', suit: 'Hearts', rank: 6, color: true },
  { name: '7 ♥️', suit: 'Hearts', rank: 7, color: true },
  { name: '8 ♥️', suit: 'Hearts', rank: 8, color: true },
  { name: '9 ♥️', suit: 'Hearts', rank: 9, color: true },
  { name: 'A ♠️', suit: 'Spades', rank: 14, color: false },
  { name: '10 ♥️', suit: 'Hearts', rank: 10, color: true },
  { name: 'J ♥️', suit: 'Hearts', rank: 11, color: true },
  { name: 'Q ♥️', suit: 'Hearts', rank: 12, color: true },
  { name: 'K ♥️', suit: 'Hearts', rank: 13, color: true },
  { name: 'A ♣️', suit: 'Clubs', rank: 14, color: false },
  { name: 'A ♦️', suit: 'Diamonds', rank: 14, color: true },

  { name: '2 ♣️', suit: 'Clubs', rank: 2, color: false },
  { name: '4 ♦️', suit: 'Diamonds', rank: 4, color: true },
  { name: '5 ♦️', suit: 'Diamonds', rank: 5, color: true },
  { name: '6 ♦️', suit: 'Diamonds', rank: 6, color: true },
  { name: '7 ♦️', suit: 'Diamonds', rank: 7, color: true },
  { name: '8 ♦️', suit: 'Diamonds', rank: 8, color: true },
  { name: '9 ♦️', suit: 'Diamonds', rank: 9, color: true },
  { name: '10 ♦️', suit: 'Diamonds', rank: 10, color: true },
  { name: 'J ♦️', suit: 'Diamonds', rank: 11, color: true },
  { name: 'Q ♦️', suit: 'Diamonds', rank: 12, color: true },
  { name: 'K ♦️', suit: 'Diamonds', rank: 13, color: true },

  { name: '3 ♣️', suit: 'Clubs', rank: 3, color: false },
  { name: '4 ♣️', suit: 'Clubs', rank: 4, color: false },
  { name: '5 ♣️', suit: 'Clubs', rank: 5, color: false },
  { name: '6 ♣️', suit: 'Clubs', rank: 6, color: false },
  { name: '7 ♣️', suit: 'Clubs', rank: 7, color: false },
  { name: '8 ♣️', suit: 'Clubs', rank: 8, color: false },
  { name: '9 ♣️', suit: 'Clubs', rank: 9, color: false },
  { name: '10 ♣️', suit: 'Clubs', rank: 10, color: false },
  { name: 'J ♣️', suit: 'Clubs', rank: 11, color: false },
  { name: 'Q ♣️', suit: 'Clubs', rank: 12, color: false },
  { name: 'K ♣️', suit: 'Clubs', rank: 13, color: false },

  { name: '3 ♠️', suit: 'Spades', rank: 3, color: false },
  { name: '4 ♠️', suit: 'Spades', rank: 4, color: false },
  { name: '5 ♠️', suit: 'Spades', rank: 5, color: false },
  { name: '6 ♠️', suit: 'Spades', rank: 6, color: false },
  { name: '7 ♠️', suit: 'Spades', rank: 7, color: false },
  { name: '8 ♠️', suit: 'Spades', rank: 8, color: false },
  { name: '9 ♠️', suit: 'Spades', rank: 9, color: false },
  { name: '10 ♠️', suit: 'Spades', rank: 10, color: false },
  { name: 'J ♠️', suit: 'Spades', rank: 11, color: false },
  { name: 'Q ♠️', suit: 'Spades', rank: 12, color: false },
  { name: 'K ♠️', suit: 'Spades', rank: 13, color: false },
];


export const fakeCard: typeCard = {
  name: 'K ♠️',
  suit: 'Spades',
  rank: 13,
  color: false
}